### ISSUE TITLE
TypeError: 'Tupperware' object is not callable

### ISSUE THREAD

**Issue by raminqaf** [valeoai/WoodScape#59]
I am trying to run the program but keep getting a `TypeError`. You can see the logs down below. I am executing the code in Google colab and all files are on Google Drive. I also tried running it locally on my machine but ran into the same `TypeError`. Any hints or solutions?

```
{
    "train": "detection",
    "dataset_dir": "/content/gdrive/MyDrive/WoodScape-master/omnidet/WoodScape_ICCV19",
    "train_file": "/content/gdrive/MyDrive/WoodScape-master/omnidet/data/train.txt",
    "val_file": "/content/gdrive/MyDrive/WoodScape-master/omnidet/data/val.txt",
    "test_file": "/content/gdrive/MyDrive/WoodScape-master/omnidet/data/test.txt",
    "output_directory": "/content/gdrive/MyDrive/WoodScape-master/omnidet/data/output",
    "model_name": "res18_baseline",
    "dataset": "woodscape_raw",
    "input_height": 288,
    "input_width": 544,
    "network_layers": 18,
    "pose_network_layers": 18,
    "frame_idxs": [
        0,
        -1
    ],
    "pose_model_type": "separate",
    "pose_model_input": "pairs",
    "rotation_mode": "euler",
    "num_scales": 4,
    "crop": true,
    "disable_auto_mask": false,
    "ego_mask": true,
    "reconstr_weight": 0.15,
    "ssim_weight": 0.85,
    "smooth_weight": 0.001,
    "clip_loss_weight": 0.5,
    "semantic_num_classes": 10,
    "semantic_loss": "focal_loss",
    "semantic_class_weighting": "woodscape_enet",
    "motion_class_weighting": "motion_enet",
    "motion_loss": "focal_loss",
    "siamese_net": true,
    "num_classes_detection": 5,
    "classes_names": [
        "vehicles",
        "person",
        "bicycle",
        "traffic_sign",
        "traffic_light"
    ],
    "detection_conf_thres": 0.8,
    "detection_nms_thres": 0.2,
    "anchors1": [
        [
            24,
            45
        ],
        [
            28,
            24
        ],
        [
            50,
            77
        ]
    ],
    "anchors2": [
        [
            52,
            39
        ],
        [
            92,
            145
        ],
        [
            101,
            69
        ]
    ],
    "anchors3": [
        [
            52,
            39
        ],
        [
            92,
            145
        ],
        [
            101,
            69
        ]
    ],
    "batch_size": 22,
    "num_workers": 6,
    "epochs": 125,
    "learning_rate": 0.0001,
    "scheduler_step_size": [
        100,
        110
    ],
    "min_distance": 0.1,
    "max_distance": 100.0,
    "log_frequency": 300,
    "val_frequency": 300,
    "save_frequency": 20,
    "weighing": "enet",
    "num_classes": 10,
    "pretrained_weights": "/content/gdrive/MyDrive/res18",
    "models_to_load": [
        "detection"
    ],
    "onnx_model": "omnidet",
    "opset_version": 12,
    "model_summary": true,
    "init_weights": true,
    "video_name": "norm",
    "model_path": "/content/gdrive/MyDrive/res18",
    "onnx_export_path": "/content/drive/MyDrive/export/",
    "onnx_load_model": "/content/gdrive/MyDrive/res18/onnx/omnidet_float32_opset12.onnx",
    "device": "cuda:0",
    "cuda_visible_devices": "0",
    "use_multiple_gpu": false
}
=> Clean up the log directory?y
=> Cleaned up the logs!
=> Training on the WOODSCAPE_RAW dataset 
=> Training model named: res18_baseline 
=> Models and tensorboard events files are saved to: /content/gdrive/MyDrive/WoodScape-master/omnidet/data/output 
=> Training is using the cuda device id: 0 
=> Loading woodscape_raw training and validation dataset
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 6 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
=> Total number of training examples: 8029 
=> Total number of validation examples: 205
=> Loading model from folder /content/gdrive/MyDrive/res18
Loading detection weights...
Cannot find {} weights so {} is randomly initialized
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/WoodScape-master/omnidet/main.py", line 109, in <module>
    main()
  File "/content/gdrive/MyDrive/WoodScape-master/omnidet/main.py", line 76, in main
    model = DetectionModel(args)
  File "/content/gdrive/MyDrive/WoodScape-master/omnidet/train_detection.py", line 277, in __init__
    self.pre_init()
  File "/content/gdrive/MyDrive/WoodScape-master/omnidet/train_detection.py", line 94, in pre_init
    self.save_args()
  File "/content/gdrive/MyDrive/WoodScape-master/omnidet/utils.py", line 135, in save_args
    yaml.dump(to_save, f)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/main.py", line 1380, in dump
    block_seq_indent=block_seq_indent,
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/main.py", line 1321, in dump_all
    dumper._representer.represent(data)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/representer.py", line 80, in represent
    node = self.represent_data(data)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/representer.py", line 103, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/representer.py", line 321, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/representer.py", line 214, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/representer.py", line 107, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/representer.py", line 447, in represent_object
    reduce = data.__reduce_ex__(2)
TypeError: 'Tupperware' object is not callable
```

**Comment by rvarun7777** [comment]
You can comment this line and try
  File "/content/gdrive/MyDrive/WoodScape-master/omnidet/utils.py", line 135, in save_args
    yaml.dump(to_save, f)

**Comment by tanutarou** [comment]
I think this issue is related to [this error](https://stackoverflow.com/questions/50888391/pickle-of-object-with-getattr-method-in-python-returns-typeerror-object-no).

Inserting the following code into [utils.py(L224)](https://github.com/valeoai/WoodScape/blob/master/omnidet/utils.py#L224) solved this problem in my environment.

```py
    def __getstate__(self):
        return self.__dict__.copy()

    def __setstate__(self, state):
        self.__dict__.update(state)

```

**Comment by raminqaf** [comment]
> You can comment this line and try File "/content/gdrive/MyDrive/WoodScape-master/omnidet/utils.py", line 135, in save_args yaml.dump(to_save, f)

This actually solved the issue! Thanks! Only commenting this code fragment in [omnidet/utils.py, line 133-134](https://github.com/valeoai/WoodScape/blob/5e585650d1583723ade75d41778ab1c995b130ed/omnidet/utils.py#L133):
```python
with open(os.path.join(models_dir, 'params.yaml'), 'w') as f:
    yaml.dump(to_save, f)
```

**Comment by rvarun7777** [comment]
The issue is primarily due to certain args in the yaml file might be invalid. When the yaml.dump op is called you'll face this issue. Hope this helps :)

**Comment by raminqaf** [comment]
> The issue is primarily due to certain args in the yaml file might be invalid. When the yaml.dump op is called you'll face this issue. Hope this helps :)

Can you please tell, which args are invalid?

**Comment by rvarun7777** [comment]
I am sorry, it depends on the local change. I have made a minor fix for the params file; take a look at it.
