### ISSUE TITLE
Training stop after 600epoch

### ISSUE THREAD

**Issue by williamhyin** [valeoai/WoodScape#79]

**Comment by williamhyin** [comment]
When I CTRL+C to stop this process, I get the traceback.


^CTraceback (most recent call last):
  File "./main.py", line 109, in <module>
    main()
  File "./main.py", line 93, in main
    model.distance_semantic_detection_motion_train()
  File "/workspace/WoodScape/omnidet/train_distance_semantic_detection_motion.py", line 77, in distance_semantic_detection_motion_train
    self.save_best_detection_weights()
  File "/workspace/WoodScape/omnidet/train_distance_semantic_detection.py", line 134, in save_best_detection_weights
    self.args.input_height])
  File "/root/miniconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/WoodScape/omnidet/train_detection.py", line 178, in detection_val
    outputs = non_max_suppression(outputs, conf_thres=conf_thres, nms_thres=nms_thres)
  File "/workspace/WoodScape/omnidet/train_utils/detection_utils.py", line 241, in non_max_suppression
    large_overlap = bbox_iou(detections[0, :4].unsqueeze(0), detections[:, :4]) > nms_thres
  File "/workspace/WoodScape/omnidet/train_utils/detection_utils.py", line 205, in bbox_iou
    b2_area = (b2_x2 - b2_x1 + 1) * (b2_y2 - b2_y1 + 1)

Is there something wrong?

**Comment by Dorablank** [comment]
Hi, were you able to solve this issue?
