### ISSUE TITLE
'Tupperware' object is not callable

### ISSUE THREAD

**Issue by blowfish9423** [valeoai/WoodScape#91]
Hi,everyone:
    when I run main.c for training,I got error below.
    I looked at this issue https://github.com/valeoai/WoodScape/issues/59, and it doesn't seem to be the same issue 
    It is Looks like iter is wrong?Can anybody help me .

a5f70.testpcurl.com
{
    "train": "motion",
    "dataset_dir": "E:/omnidet_data/WoodScape_ICCV19/",
    "train_file": "E:/WoodScape/omnidet/data/train.txt",
    "val_file": "E:/WoodScape/omnidet/data/val.txt",
    "test_file": "E:/WoodScape/omnidet/data/test.txt",
    "output_directory": "E:/WoodScape/WoodScape_ICCV19/output/",
    "model_name": "res18_baseline",
    "dataset": "woodscape_raw",
    "input_height": 288,
    "input_width": 544,
    "network_layers": 18,
    "pose_network_layers": 18,
    "frame_idxs": [
        0,
        -1
    ],
    "pose_model_type": "separate",
    "pose_model_input": "pairs",
    "rotation_mode": "euler",
    "num_scales": 4,
    "crop": true,
    "disable_auto_mask": false,
    "ego_mask": true,
    "reconstr_weight": 0.15,
    "ssim_weight": 0.85,
    "smooth_weight": 0.001,
    "clip_loss_weight": 0.5,
    "semantic_num_classes": 10,
    "semantic_loss": "focal_loss",
    "semantic_class_weighting": "woodscape_enet",
    "motion_class_weighting": "motion_enet",
    "motion_loss": "focal_loss",
    "siamese_net": true,
    "num_classes_detection": 5,
    "classes_names": [
        "vehicles",
        "person",
        "bicycle",
        "traffic_sign",
        "traffic_light"
    ],
    "detection_conf_thres": 0.8,
    "detection_nms_thres": 0.2,
    "anchors1": [
        [
            24,
            45
        ],
        [
            28,
            24
        ],
        [
            50,
            77
        ]
    ],
    "anchors2": [
        [
            52,
            39
        ],
        [
            92,
            145
        ],
        [
            101,
            69
        ]
    ],
    "anchors3": [
        [
            52,
            39
        ],
        [
            92,
            145
        ],
        [
            101,
            69
        ]
    ],
    "batch_size": 1,
    "num_workers": 1,
    "epochs": 125,
    "learning_rate": 0.0001,
    "scheduler_step_size": [
        100,
        110
    ],
    "min_distance": 0.1,
    "max_distance": 100.0,
    "log_frequency": 300,
    "val_frequency": 300,
    "save_frequency": 20,
    "weighing": "enet",
    "num_classes": 10,
    "pretrained_weights": null,
    "models_to_load": [
        "encoder",
        "detection"
    ],
    "onnx_model": "omnidet",
    "opset_version": 12,
    "model_summary": true,
    "init_weights": true,
    "video_name": "norm",
    "model_path": null,
    "onnx_export_path": null,
    "onnx_load_model": null,
    "device": "cuda:0",
    "cuda_visible_devices": "0",
    "use_multiple_gpu": false
}
=> Clean up the log directory?y
=> Cleaned up the logs!
=> Setting Class weights based on: motion_enet
=> [1.45, 23.36]
=> Training on the WOODSCAPE_RAW dataset 
=> Training model named: res18_baseline
=> Models and tensorboard events files are saved to: E:/WoodScape/WoodScape_ICCV19/output/
=> Training is using the cuda device id: 0
=> Loading woodscape_raw training and validation dataset
=> Total number of training examples: 8029 
=> Total number of validation examples: 205
Traceback (most recent call last):
  File "e:\WoodScape\omnidet\main.py", line 109, in <module>
    main()
  File "e:\WoodScape\omnidet\main.py", line 74, in main
    model.motion_train()
  File "e:\WoodScape\omnidet\train_motion.py", line 121, in motion_train
    for batch_idx, inputs in enumerate(self.train_loader):
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\multiprocessing\process.py", line 105, in start        
    self._popen = self._Popen(self)
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\blowfish-G7\Anaconda3\envs\PyTorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'Tupperware' object is not callable

**Comment by blowfish9423** [comment]
=> Training on the WOODSCAPE_RAW projection model 
=> Training model named: res18_baseline
=> Models and tensorboard events files are saved to: E:/WoodScape/omnidet/data/output
=> Loading woodscape_raw training and validation dataset
=> Total number of training examples: 8029
Traceback (most recent call last):
  File "e:\WoodScape\omnidet\main.py", line 109, in <module>
    main()
  File "e:\WoodScape\omnidet\main.py", line 92, in main
    model = DistanceSemanticDetectionMotionModel(args)
  File "e:\WoodScape\omnidet\train_distance_semantic_detection_motion.py", line 25, in __init__
    super().__init__(args)
  File "e:\WoodScape\omnidet\train_distance_semantic_detection.py", line 30, in __init__
    super().__init__(args)
  File "e:\WoodScape\omnidet\train_distance_semantic_motion.py", line 25, in __init__
    super().__init__(args)
  File "e:\WoodScape\omnidet\train_distance_semantic.py", line 24, in __init__
    super().__init__(args)
  File "e:\WoodScape\omnidet\train_distance.py", line 94, in __init__
    self.val_iter = iter(self.val_loader)
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\chuan_li\AppData\Local\conda\conda\envs\PyTorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'Tupperware' object is not callable

**Comment by blowfish9423** [comment]
xception has occurred: TypeError
'Tupperware' object is not callable
  File "[E:\WoodScape\omnidet\train_motion.py]()", line 121, in motion_train
    for batch_idx, inputs in enumerate(self.train_loader):
  File "[E:\WoodScape\omnidet\main.py]()", line 74, in main
    model.motion_train()
  File "[E:\WoodScape\omnidet\main.py]()", line 109, in <module>
    main()

**Comment by blowfish9423** [comment]
I found this problem is in window10/11,linux is OK.I don't know why.

**Comment by RaymondLmx** [comment]
In my experiment, linux is not OK too.

**Comment by Dorablank** [comment]
出现这个问题需要将 num_workers 设置为0，windows下不支持多进程读取数据。

**Comment by Dorablank** [comment]
此外，你们有没有试过评估检测模型的MAP？我这边评估出来的指标只有0.06。

**Comment by Shiwen615** [comment]
The Tupperware class is related to argparse. Maybe there are some arguments you haven’t assigned
